# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wedbrowser.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtWebEngineWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(92, 37)
        Form.setMinimumSize(QtCore.QSize(92, 37))
        Form.setMaximumSize(QtCore.QSize(92, 37))
        Form.setWindowFlags(QtCore.Qt.WindowTitleHint | QtCore.Qt.WindowCloseButtonHint)
        font = QtGui.QFont()
        font.setPointSize(8)
        Form.setFont(font)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(-20, -70, 131, 171))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.pushButton.clicked.connect(self.message)
        self.pushButton.clicked.connect(Form.close)

    def message(self):
        QtWidgets.QMessageBox.information(MainWindow, ":)", "I am not annoyed\nI am kind :)\nThanks! (:")


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", ":/?"))
        self.pushButton.setText(_translate("Form", ":/"))



class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(285, 103)
        Dialog.setMinimumSize(QtCore.QSize(285, 103))
        Dialog.setMaximumSize(QtCore.QSize(285, 103))
        Dialog.setModal(True)
        Dialog.setWindowFlags(QtCore.Qt.WindowTitleHint | QtCore.Qt.WindowCloseButtonHint)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(120, 70, 156, 23))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.filenameEdit = QtWidgets.QLineEdit(Dialog)
        self.filenameEdit.setGeometry(QtCore.QRect(10, 20, 271, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filenameEdit.sizePolicy().hasHeightForWidth())
        self.filenameEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.filenameEdit.setFont(font)
        self.filenameEdit.setObjectName("filenameEdit")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Filename"))
        self.filenameEdit.setPlaceholderText(_translate("Dialog", 'Type a Filename... (To PDF⇒Filename.pdf)'))



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(892, 560)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.backButton = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backButton.sizePolicy().hasHeightForWidth())
        self.backButton.setSizePolicy(sizePolicy)
        self.backButton.setArrowType(QtCore.Qt.LeftArrow)
        self.backButton.setObjectName("backButton")
        self.horizontalLayout.addWidget(self.backButton)
        self.forwardButton = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forwardButton.sizePolicy().hasHeightForWidth())
        self.forwardButton.setSizePolicy(sizePolicy)
        self.forwardButton.setArrowType(QtCore.Qt.RightArrow)
        self.forwardButton.setObjectName("forwardButton")
        self.horizontalLayout.addWidget(self.forwardButton)
        self.reloadButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reloadButton.sizePolicy().hasHeightForWidth())
        self.reloadButton.setSizePolicy(sizePolicy)
        self.reloadButton.setObjectName("reloadButton")
        self.horizontalLayout.addWidget(self.reloadButton)
        self.googleButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.googleButton.sizePolicy().hasHeightForWidth())
        self.googleButton.setSizePolicy(sizePolicy)
        self.googleButton.setObjectName("googleButton")
        self.horizontalLayout.addWidget(self.googleButton)
        self.urlEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.urlEdit.sizePolicy().hasHeightForWidth())
        self.urlEdit.setSizePolicy(sizePolicy)
        self.urlEdit.setObjectName("urlEdit")
        self.horizontalLayout.addWidget(self.urlEdit)
        self.goButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goButton.sizePolicy().hasHeightForWidth())
        self.goButton.setSizePolicy(sizePolicy)
        self.goButton.setObjectName("goButton")
        self.horizontalLayout.addWidget(self.goButton)
        self.pdfButton = QtWidgets.QPushButton(self.centralwidget)
        self.pdfButton.setObjectName("pdfButton")
        self.horizontalLayout.addWidget(self.pdfButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.webBrowser = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        self.webBrowser.setObjectName("webBrowser")
        self.verticalLayout.addWidget(self.webBrowser)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 892, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.googleButton.clicked.connect(lambda: self.webBrowser.setUrl(QtCore.QUrl("https://google.com")))
        self.goButton.clicked.connect(lambda: self.webBrowser.setUrl(QtCore.QUrl(self.urlEdit.text())))
        self.backButton.clicked.connect(self.webBrowser.back)
        self.forwardButton.clicked.connect(self.webBrowser.forward)
        self.reloadButton.clicked.connect(self.webBrowser.reload)

        self.webBrowser.urlChanged.connect(lambda u: self.urlEdit.setText(u.toString()))
        self.webBrowser.iconChanged.connect(lambda i: MainWindow.setWindowIcon(i))
        self.webBrowser.titleChanged.connect(lambda t: MainWindow.setWindowTitle(t))

        url_display_options = QtCore.QUrl.RemoveScheme | QtCore.QUrl.RemovePath | QtCore.QUrl.RemoveQuery
        self.webBrowser.loadStarted.connect(lambda: self.statusbar.showMessage("Started loading " + self.webBrowser.url().toString(url_display_options)[2:] + "...", 2 * 1000))
        self.webBrowser.loadProgress.connect(lambda p: self.statusbar.showMessage("Loading " + self.webBrowser.url().toString(url_display_options)[2:] + "... (" + str(p) + ")"))
        self.webBrowser.loadFinished.connect(lambda: self.statusbar.showMessage("Done.", 2 * 1000))

        self.pdfButton.clicked.connect(self.filename_input)
        self.webBrowser.page().pdfPrintingFinished.connect(self.printing_finished)

    def printing_finished(self, path, ok):
        if ok:
            QtWidgets.QMessageBox.information(self.webBrowser, "Print to PDF", "Printing to " + path + " is complete")
        elif not ok:
            QtWidgets.QMessageBox.critical(self.webBrowser, "Print to PDF", "Printing to " + path + " has failed")
        else:
            print(":/")

    def filename_input(self):
        Dialog = QtWidgets.QDialog()
        ui2 = Ui_Dialog()
        ui2.setupUi(Dialog)
        Dialog.move(MainWindow.geometry().center() - Dialog.rect().center() - QtCore.QPoint(0, 35))
        Dialog.show()
        result = Dialog.exec()
        if result == 1:
            filename = ui2.filenameEdit.text()
            if filename:
                self.webBrowser.page().printToPdf(filename)

    def smile(self):
        Form = QtWidgets.QDialog()
        ui3 = Ui_Form()
        ui3.setupUi(Form)
        Form.move(QtCore.QPoint(0, 0))
        Form.show()
        Form.exec()



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Wed Browser"))
        self.backButton.setText(_translate("MainWindow", "..."))
        self.forwardButton.setText(_translate("MainWindow", "..."))
        self.reloadButton.setText(_translate("MainWindow", "Reload"))
        self.googleButton.setText(_translate("MainWindow", "Google"))
        self.goButton.setText(_translate("MainWindow", "Go"))
        self.pdfButton.setText(_translate("MainWindow", "To PDF"))

        self.quit_sh = QtWidgets.QShortcut(QtGui.QKeySequence("Ctrl+Q"), MainWindow)
        self.quit_sh.activated.connect(MainWindow.close)

        self.smile_sh = QtWidgets.QShortcut(QtGui.QKeySequence("Ctrl+Shift+S"), MainWindow)
        self.smile_sh.activated.connect(self.smile)

        self.urlEdit.returnPressed.connect(self.goButton.click)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
